#' musoSensi
#'
#' Sensitivity analysis for Biome-BGCMuSo based on the output of musoMonte.
#' Supports two methods:
#'   \describe{
#'     \item{"src"}{Standardized Regression Coefficients (default). Fits a linear
#'       model across all Monte Carlo samples and partitions output variance by
#'       parameter. Fast but assumes linearity.}
#'     \item{"boruta"}{Random Forest variable importance via the Boruta algorithm.
#'       Identifies which parameters significantly affect the output without
#'       assuming linearity. Returns Confirmed/Tentative/Rejected decisions.
#'       Requires the \pkg{Boruta} package.}
#'   }
#' @param monteCarloFile Path to a previously saved preservedEpc CSV. If NULL,
#'   musoMonte is run internally.
#' @param settings A list of Monte Carlo environmental variables generated by
#'   setupMuso(). Used only when monteCarloFile is NULL.
#' @param parameters Dataframe with columns: name, EPC row number, min, max.
#' @param inputDir Location of the model input directory.
#' @param outLoc Output directory for Monte Carlo CSV files.
#' @param outVars Output variables to track.
#' @param iterations Number of Monte Carlo runs (used when monteCarloFile is NULL).
#' @param preTag Prefix for Monte Carlo output file names.
#' @param outputType "moreCsv" (default), "oneCsv", or "netCDF".
#' @param fun Aggregation function applied to the time-series model output (default: mean).
#' @param varIndex Which output variable to use as the sensitivity target (1-based).
#' @param outputFile Path for the sensitivity results CSV.
#' @param plotName Path for the sensitivity bar chart PNG.
#' @param plotTitle Title for the sensitivity plot.
#' @param skipSpinup Skip spinup phase after the first run.
#' @param skipZero Replace zero model outputs with NA.
#' @param sourceFile Optional source EPC file.
#' @param postProcString Optional post-processing expression string.
#' @param constraints Parameter constraints passed to musoRand.
#' @param modifyOut Whether to modify the original EPC (TRUE) or a copy.
#' @param dpi Resolution for the saved plot.
#' @param method Sensitivity method: \code{"src"} (Standardized Regression
#'   Coefficients, default) or \code{"boruta"} (Random Forest importance).
#' @param parallel If TRUE, Monte Carlo model runs are parallelised using
#'   doParallel + foreach. Passed through to musoMonte. Default FALSE.
#' @param nCores Number of parallel workers. NULL uses detectCores() - 1.
#' @param sampling Passed through to musoMonte. \code{"auto"} (default)
#'   auto-detects constraints and chooses LHS or MCMC accordingly.
#' @param borutaMaxRuns Maximum number of Boruta iterations (default 100).
#' @param borutaDoTrace Verbosity level for Boruta (0 = silent).
#' @param borutaEngine Which random forest backend Boruta should use for
#'   importance. Boruta 10.0.0 switched its default from \pkg{ranger}
#'   (\code{getImpRfZ}) to the Rust-based \pkg{fru} (\code{getImpFruZ}), and
#'   the two take different parameter names, so the tuned settings have to be
#'   translated. One of:
#'   \describe{
#'     \item{"auto"}{(default) Use fru when the installed Boruta provides
#'       \code{getImpFruZ}, otherwise ranger.}
#'     \item{"fru"}{Force fru. Faster, but its leaf-size threshold is fixed
#'       (4 for regression), so \code{min.node.size} cannot be applied.}
#'     \item{"ranger"}{Force ranger. Slower, but accepts all three tuned
#'       parameters and matches the engine used for the SHAP surrogate.}
#'   }
#' @param shap If TRUE, SHAP (SHapley Additive exPlanations) values are computed
#'   in addition to the Boruta decisions. Requires the \pkg{ranger} and
#'   \pkg{fastshap} packages. Ignored when \code{method = "src"}. Default FALSE.
#' @param shapEngine Which SHAP implementation to use:
#'   \describe{
#'     \item{"auto"}{(default) Use the first of \pkg{treeshap},
#'       \pkg{kernelshap}, \pkg{fastshap} that is installed. The engine
#'       actually selected is reported in a message.}
#'     \item{"treeshap"}{Exact TreeSHAP for the ranger surrogate. Fastest and
#'       exact rather than approximate, so \code{shapNsim} is ignored. On CRAN.}
#'     \item{"kernelshap"}{Model-agnostic Kernel SHAP. Exact for small
#'       parameter counts, otherwise iterates to a standard-error target.
#'       On CRAN.}
#'     \item{"fastshap"}{Monte Carlo Shapley sampling. NOTE: fastshap was
#'       archived from CRAN on 2026-05-27. It still works, but must be
#'       installed from r-universe:
#'       \code{install.packages("fastshap",
#'       repos = c("https://bgreenwell.r-universe.dev",
#'       "https://cloud.r-project.org"))}}
#'   }
#' @param shapNsim Number of Monte Carlo repetitions used to approximate the
#'   Shapley values. Applies to \code{shapEngine = "fastshap"} only; treeshap
#'   is exact and kernelshap manages its own iteration. Higher is more
#'   accurate but slower; cost scales as nsim x nParameters x nSamples.
#'   Default 100.
#' @param shapBgN Background sample size for \code{shapEngine = "kernelshap"}.
#'   Default 200.
#' @param shapNtree Number of trees in the random forest surrogate model fitted
#'   before the SHAP computation. Default 500.
#' @param shapOutputFile Path for the per-sample SHAP value CSV.
#' @param shapSummaryFile Path for the mean absolute SHAP importance CSV.
#' @param shapPlotName Path for the SHAP beeswarm summary plot PNG.
#' @param shapImpPlotName Path for the mean absolute SHAP bar chart PNG.
#' @param shapTopN Show only the \code{shapTopN} most important parameters in
#'   the plots. NULL (default) shows all of them.
#' @param shapSeed Random seed for the surrogate forest and the SHAP sampling,
#'   for reproducibility. NULL disables seeding.
#' @param rfTune Controls the automatic random forest hyperparameter advisor
#'   (see \code{\link{musoRFTune}}), which scales \code{num.trees},
#'   \code{mtry} and \code{min.node.size} to the size of the Monte Carlo
#'   design. One of:
#'   \describe{
#'     \item{"ask"}{(default) Print a recommendation and prompt for
#'       confirmation in interactive sessions; apply automatically under
#'       Rscript or inside parallel workers so batch runs never block.}
#'     \item{"auto"}{Apply the recommendation silently.}
#'     \item{"off"}{Keep the ranger/Boruta defaults.}
#'   }
#'   Ignored when \code{method = "src"}.
#' @param rfRefine If TRUE (default) the advisor refines its heuristic seed
#'   with a small out-of-bag grid search on the actual Monte Carlo data.
#' @param mtry Explicit mtry for the forests. Overrides the advisor when set.
#' @param minNodeSize Explicit min.node.size. Overrides the advisor when set.
#' @return For \code{method = "src"} a named numeric vector of percentage
#'   variance contributions. For \code{method = "boruta"} the Boruta object
#'   (invisibly). When \code{shap = TRUE} a list is returned invisibly with
#'   elements \code{boruta}, \code{borutaImportance} and \code{shap}; the
#'   latter holds \code{shapValues} (per-sample SHAP matrix),
#'   \code{importance} (mean |SHAP| table), \code{surrogateR2} and the two
#'   ggplot objects.
#' @importFrom ggplot2 geom_bar ggplot aes theme element_text xlab ylab ggtitle ggsave scale_y_continuous scale_fill_manual geom_hline geom_jitter coord_flip scale_colour_gradient
#' @importFrom scales percent
#' @importFrom stats lm var predict reformulate
#' @export

musoSensi <- function(monteCarloFile = NULL,
                     parameters = NULL,
                     settings = NULL,
                     inputDir = "./",
                     outLoc = "./calib",
                     outVars = NULL,
                     iterations = 30,
                     preTag = "mont-",
                     outputType = "moreCsv",
                     fun = mean,
                     varIndex = 1,
                     outputFile = "sensitivity.csv",
                     plotName = "sensitivity.png",
                     plotTitle = "Sensitivity",
                     skipSpinup = TRUE,
                     skipZero = TRUE,
                     sourceFile = NULL,
                     postProcString = NULL,
                     constraints = NULL,
                     modifyOut = TRUE,
                     dpi = 300,
                     method = "src",
                     parallel = FALSE,
                     nCores = NULL,
                     sampling = "auto",
                     borutaMaxRuns = 100,
                     borutaDoTrace = 0,
                     borutaEngine = "auto",
                     shap = FALSE,
                     shapEngine = "auto",
                     shapNsim = 100,
                     shapBgN = 200,
                     shapNtree = 500,
                     shapOutputFile = "shap_values.csv",
                     shapSummaryFile = "shap_importance.csv",
                     shapPlotName = "shap_beeswarm.png",
                     shapImpPlotName = "shap_importance.png",
                     shapTopN = NULL,
                     shapSeed = NULL,
                     rfTune = "ask",
                     rfRefine = TRUE,
                     mtry = NULL,
                     minNodeSize = NULL){

    method     <- match.arg(method, c("src", "boruta"))
    rfTune     <- match.arg(rfTune, c("ask", "auto", "off"))
    shapEngine <- match.arg(shapEngine,
                            c("auto", "treeshap", "kernelshap", "fastshap"))
    borutaEngine <- match.arg(borutaEngine, c("auto", "fru", "ranger"))

    # Captured here because missing() only works on the formals of the
    # function it is called in, not from inside the nested doShap closure.
    shapNtreeUserSet <- !missing(shapNtree)

    if(shap && method == "src"){
        warning("shap = TRUE is only supported for method = 'boruta'; ignoring.")
        shap <- FALSE
    }

    if(is.null(parameters)){
        parameters <- tryCatch(read.csv("parameters.csv",stringsAsFactor=FALSE), error = function (e) {
            stop("You need to specify a path for the parameters.csv, or a matrix.")
        })
    } else {
        if((!is.list(parameters)) & (!is.matrix(parameters))){
             parameters <- tryCatch(read.csv(parameters,stringsAsFactor=FALSE), error = function (e){
                                         stop("Cannot find neither parameters file neither the parameters matrix")
                                     })
        }}
    parameters[,1] <- gsub("([\\s]|\\-epc)","",parameters[,1],perl=TRUE)

    # -------------------------------------------------------------------------
    # SHAP (SHapley Additive exPlanations)
    #
    # Boruta answers "does this parameter matter at all?" with a yes/no/maybe
    # decision. SHAP answers the complementary questions: how much does each
    # parameter contribute to each individual model run, and in which
    # direction. A random forest surrogate is fitted on the Monte Carlo cloud
    # and Shapley values are approximated with fastshap's Monte Carlo sampler.
    #
    # Returns a list with the raw SHAP matrix, the mean |SHAP| importance
    # table and both ggplot objects.
    # -------------------------------------------------------------------------
    doShap <- function(M_df, y, varNames, rfSet = NULL){

        has <- function(p) requireNamespace(p, quietly = TRUE)

        if(!has("ranger")){
            stop("Package 'ranger' is required for shap = TRUE.\n",
                 "Install with: install.packages('ranger')")
        }

        # ------------------------------------------------------------------
        # Resolve the SHAP engine.
        #
        # fastshap was archived from CRAN on 2026-05-27, so it can no longer
        # be relied on as a default. treeshap and kernelshap are both on CRAN
        # and both support ranger; treeshap is preferred because TreeSHAP is
        # exact for tree ensembles, removing the nsim accuracy/speed
        # tradeoff entirely. fastshap is still honoured when explicitly
        # requested or when it is the only engine present.
        # ------------------------------------------------------------------
        engineOrder <- c("treeshap", "kernelshap", "fastshap")
        engine <- if(shapEngine == "auto"){
            avail <- engineOrder[vapply(engineOrder, has, logical(1))]
            if(length(avail) == 0) NA_character_ else avail[1]
        } else {
            if(!has(shapEngine)) NA_character_ else shapEngine
        }

        if(is.na(engine)){
            fastshapHint <- paste0(
                "  fastshap   (archived from CRAN 2026-05-27, still maintained):\n",
                "    install.packages(\"fastshap\", repos = c(\n",
                "      \"https://bgreenwell.r-universe.dev\",\n",
                "      \"https://cloud.r-project.org\"))\n",
                "    # or: remotes::install_github(\"bgreenwell/fastshap\", ref = \"devel\")\n",
                "    # (the GitHub route compiles C++, so it needs Rtools on Windows;\n",
                "    #  r-universe ships prebuilt binaries and does not)")
            if(shapEngine == "auto"){
                stop("shap = TRUE needs a SHAP engine, but none of ",
                     "'treeshap', 'kernelshap' or 'fastshap' is installed.\n\n",
                     "Recommended (CRAN, exact for tree models):\n",
                     "    install.packages(\"treeshap\")\n\n",
                     "Alternative (CRAN, model-agnostic):\n",
                     "    install.packages(\"kernelshap\")\n\n",
                     fastshapHint)
            } else if(shapEngine == "fastshap"){
                stop("shapEngine = \"fastshap\" was requested but the package is not installed.\n\n",
                     fastshapHint)
            } else {
                stop(sprintf("shapEngine = \"%s\" was requested but the package is not installed.\n",
                             shapEngine),
                     sprintf("    install.packages(\"%s\")", shapEngine))
            }
        }
        message(sprintf("SHAP engine: %s", engine))

        if(!is.null(shapSeed)){
            set.seed(shapSeed)
        }

        # ranger needs syntactically valid column names; keep a map back to the
        # original parameter names for the output files and plots.
        safeNames <- make.names(varNames, unique = TRUE)
        trainDf   <- as.data.frame(M_df)
        colnames(trainDf) <- safeNames

        # Response column name must not collide with any parameter name.
        yName <- "musoTargetY"
        while(yName %in% safeNames){
            yName <- paste0(yName, ".")
        }
        trainDf[[yName]] <- y

        # Advisor values when available, otherwise the explicit shapNtree /
        # ranger defaults. rfSet is expressed in the real p-column space here,
        # so no shadow rescaling is applied.
        rfArgs <- list(
            formula    = stats::reformulate(safeNames, response = yName),
            data       = trainDf,
            num.trees  = shapNtree,
            importance = "none"
        )
        if(!is.null(rfSet)){
            if(!shapNtreeUserSet) rfArgs$num.trees <- rfSet$num.trees
            rfArgs$mtry          <- max(1L, min(length(safeNames),
                                                as.integer(rfSet$mtry)))
            rfArgs$min.node.size <- rfSet$min.node.size
            message(sprintf("SHAP surrogate: num.trees = %d, mtry = %d (of %d), min.node.size = %d",
                            rfArgs$num.trees, rfArgs$mtry, length(safeNames),
                            rfArgs$min.node.size))
        }

        message("Fitting random forest surrogate for SHAP ...")
        rf <- do.call(ranger::ranger, rfArgs)

        # Explained R^2 of the surrogate. SHAP values are only as meaningful as
        # the surrogate that produced them, so this is reported to the user.
        oobPred <- rf$predictions
        surrR2  <- if(!is.null(oobPred)){
            1 - sum((y - oobPred)^2, na.rm = TRUE) /
                sum((y - mean(y, na.rm = TRUE))^2, na.rm = TRUE)
        } else NA_real_
        message(sprintf("Surrogate random forest OOB R2: %.3f", surrR2))
        if(!is.na(surrR2) && surrR2 < 0.5){
            warning(sprintf(paste0("The random forest surrogate explains only %.1f%% of the ",
                                   "output variance (OOB R2). SHAP values may be unreliable; ",
                                   "consider increasing the number of Monte Carlo iterations."),
                            surrR2 * 100))
        }

        featureDf <- trainDf[, safeNames, drop = FALSE]

        # ------------------------------------------------------------------
        # Engine dispatch. Each branch must return a plain numeric matrix of
        # dimension nrow(featureDf) x length(safeNames), in column order.
        # ------------------------------------------------------------------
        shapMat <- switch(engine,

            "treeshap" = {
                message(sprintf("Computing exact TreeSHAP values (%d parameters, %d samples) ...",
                                length(safeNames), nrow(featureDf)))
                unified <- treeshap::ranger.unify(rf, featureDf)
                ts      <- treeshap::treeshap(unified, featureDf, verbose = FALSE)
                as.matrix(as.data.frame(ts$shaps))
            },

            "kernelshap" = {
                message(sprintf("Computing Kernel SHAP values (%d parameters, %d samples) ...",
                                length(safeNames), nrow(featureDf)))
                bgN <- min(shapBgN, nrow(featureDf))
                ks  <- kernelshap::kernelshap(
                    rf,
                    X        = featureDf,
                    bg_X     = featureDf[sample(nrow(featureDf), bgN), , drop = FALSE],
                    pred_fun = function(object, X, ...) predict(object, X, ...)$predictions,
                    verbose  = FALSE
                )
                as.matrix(ks$S)
            },

            "fastshap" = {
                message(sprintf("Computing SHAP values (nsim = %d, %d parameters, %d samples) ...",
                                shapNsim, length(safeNames), nrow(featureDf)))
                fs <- fastshap::explain(
                    rf,
                    X            = featureDf,
                    pred_wrapper = function(object, newdata){
                        predict(object, data = newdata)$predictions
                    },
                    nsim         = shapNsim
                )
                as.matrix(as.data.frame(fs))
            }
        )

        if(is.null(dim(shapMat)) || ncol(shapMat) != length(varNames) ||
           nrow(shapMat) != nrow(featureDf)){
            stop(sprintf(paste0("SHAP engine '%s' returned a %s result; expected a %d x %d matrix. ",
                                "This usually means the engine's API has changed."),
                         engine, paste(dim(shapMat), collapse = " x "),
                         nrow(featureDf), length(varNames)))
        }

        # Engines may reorder or rename columns; realign to the training
        # feature order before restoring the original parameter names.
        if(!is.null(colnames(shapMat)) && all(safeNames %in% colnames(shapMat))){
            shapMat <- shapMat[, safeNames, drop = FALSE]
        }
        colnames(shapMat) <- varNames
        storage.mode(shapMat) <- "double"

        # ---- global importance: mean absolute SHAP value per parameter ------
        meanAbsShap <- colMeans(abs(shapMat), na.rm = TRUE)
        meanShap    <- colMeans(shapMat, na.rm = TRUE)
        shapImp <- data.frame(
            parameter       = varNames,
            meanAbsShap     = as.numeric(meanAbsShap),
            meanShap        = as.numeric(meanShap),
            relImportance   = if(sum(meanAbsShap, na.rm = TRUE) > 0){
                                  as.numeric(meanAbsShap / sum(meanAbsShap, na.rm = TRUE)) * 100
                              } else rep(0, length(varNames)),
            row.names       = NULL,
            stringsAsFactors = FALSE
        )
        shapImp <- shapImp[order(-shapImp$meanAbsShap), ]
        rownames(shapImp) <- NULL

        shapOut <- as.data.frame(shapMat)
        colnames(shapOut) <- varNames
        write.csv(shapOut, file = shapOutputFile, row.names = FALSE)
        write.csv(shapImp, file = shapSummaryFile, row.names = FALSE)

        # ---- which parameters end up in the figures -------------------------
        plotVars <- shapImp$parameter
        if(!is.null(shapTopN) && is.finite(shapTopN) && shapTopN < length(plotVars)){
            plotVars <- plotVars[seq_len(shapTopN)]
        }
        varOrder <- rev(plotVars)   # most important on top after coord_flip

        # ---- long-format data for the beeswarm ------------------------------
        longList <- lapply(plotVars, function(v){
            featVal <- M_df[[match(v, varNames)]]
            rng     <- range(featVal, na.rm = TRUE)
            scaled  <- if(diff(rng) > 0) (featVal - rng[1]) / diff(rng) else rep(0.5, length(featVal))
            data.frame(parameter  = v,
                       shapValue  = shapMat[, v],
                       featScaled = scaled,
                       stringsAsFactors = FALSE)
        })
        shapLong <- do.call(rbind, longList)
        shapLong$parameter <- factor(shapLong$parameter, levels = varOrder)

        # ---- beeswarm summary plot ------------------------------------------
        # geom_jitter is used rather than ggbeeswarm to avoid an extra
        # dependency; the vertical jitter reproduces the familiar SHAP
        # "violin of points" look closely enough.
        beePlot <- ggplot(shapLong,
                          aes(x = parameter, y = shapValue, colour = featScaled)) +
            geom_hline(yintercept = 0, colour = "grey50") +
            ggplot2::geom_jitter(width = 0.22, height = 0, alpha = 0.6, size = 1.4) +
            scale_colour_gradient(low = "#2c7fb8", high = "#e6550d",
                                  breaks = c(0, 1), labels = c("low", "high"),
                                  name = "Parameter\nvalue") +
            coord_flip() +
            xlab(NULL) +
            ylab("SHAP value (impact on model output)") +
            ggtitle(paste0(plotTitle, " - SHAP summary")) +
            theme(axis.text.y = element_text(size = 8))

        # ---- mean |SHAP| bar chart ------------------------------------------
        impPlotData <- shapImp[shapImp$parameter %in% plotVars, , drop = FALSE]
        impPlotData$parameter <- factor(impPlotData$parameter, levels = varOrder)

        impPlot <- ggplot(impPlotData, aes(x = parameter, y = meanAbsShap)) +
            geom_bar(stat = "identity", fill = "steelblue") +
            coord_flip() +
            xlab(NULL) +
            ylab("mean(|SHAP value|)") +
            ggtitle(paste0(plotTitle, " - SHAP importance")) +
            theme(axis.text.y = element_text(size = 8))

        print(beePlot)
        ggsave(shapPlotName, plot = beePlot, dpi = dpi)
        print(impPlot)
        ggsave(shapImpPlotName, plot = impPlot, dpi = dpi)

        message(sprintf("SHAP results written to '%s' and '%s'; figures: '%s', '%s'.",
                        shapOutputFile, shapSummaryFile, shapPlotName, shapImpPlotName))

        list(shapValues     = shapOut,
             importance     = shapImp,
             surrogateR2    = surrR2,
             engine         = engine,
             beeswarmPlot   = beePlot,
             importancePlot = impPlot)
    }

    # -------------------------------------------------------------------------
    # Inner analysis function: receives assembled Monte Carlo matrix M where
    # the last column is the model output and the rest are parameter values.
    # -------------------------------------------------------------------------
    doSensi <- function(M){
        npar <- ncol(M) - 1
        M <- M[which(!is.na(M[, ncol(M)])), ]
        M <- M[-1, ]
        y <- M[, (npar + 1)]
        colnames(M) <- gsub("\\.epc", "-epc", colnames(M))
        M <- M[, colnames(M) %in% parameters[, 1], drop = FALSE]
        npar <- ncol(M)
        varNames <- colnames(M)

        if(method == "src"){
            # ------------------------------------------------------------------
            # Standardized Regression Coefficients
            # ------------------------------------------------------------------
            M_c <- apply(M, 2, function(x){ x - mean(x) })
            w <- lm(y ~ M_c)$coefficients[-1]
            Sv <- apply(M_c, 2, var)
            overalVar <- sum(Sv * w^2, na.rm = TRUE)
            S <- numeric(npar)
            for(i in 1:npar){
                S[i] <- ((w[i]^2 * Sv[i]) / overalVar) * 100
            }
            S <- round(S, digits = 2)
            names(S) <- varNames
            write.csv(file = outputFile, x = S)

            sensiPlot <- ggplot(data.frame(name = varNames, y = S / 100),
                                aes(x = name, y = y)) +
                geom_bar(stat = 'identity') +
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab(NULL) +
                ylab(NULL) +
                ggtitle(plotTitle) +
                scale_y_continuous(labels = scales::percent, limits = c(0, 1))
            print(sensiPlot)
            ggsave(plotName, dpi = dpi)
            return(S)

        } else if(method == "boruta"){
            # ------------------------------------------------------------------
            # Boruta: Random Forest variable importance
            # ------------------------------------------------------------------
            if(!requireNamespace("Boruta", quietly = TRUE)){
                stop(paste0("Package 'Boruta' is required for method='boruta'.\n",
                            "Install with: install.packages('Boruta')"))
            }

            M_df <- as.data.frame(M)

            # ------------------------------------------------------------------
            # Random forest hyperparameter advisor.
            #
            # Run once on the real Monte Carlo data (forBoruta = FALSE) and
            # reuse the result for both forests. Boruta appends one shadow
            # copy per parameter, so its feature space is 2p wide and mtry has
            # to be rescaled accordingly - otherwise a value chosen for p
            # columns silently becomes twice as restrictive there.
            #
            # The obvious worry is that a large mtry lets real parameters win
            # every split, deflating the shadow-importance threshold and
            # inflating false positives. Simulation (n = 60, p = 15, three
            # informative parameters) says otherwise: as mtry/2p went from
            # 0.13 to 1.0 the false positive rate on inert parameters fell
            # slightly (0.067 -> 0.054) while the detection rate rose
            # (0.87 -> 0.98). The scaling is therefore applied in full rather
            # than capped.
            # ------------------------------------------------------------------
            rfSet <- NULL
            if(rfTune != "off" || !is.null(mtry) || !is.null(minNodeSize)){
                # No point paying for an OOB search whose result will be
                # discarded because tuning is off.
                rfRec <- musoRFTune(n = nrow(M_df), p = ncol(M_df),
                                    X = M_df, y = y,
                                    refine = rfRefine && rfTune != "off",
                                    forBoruta = FALSE,
                                    quiet = (rfTune == "off"))
                rfSet <- musoRFTuneApply(
                    rfRec,
                    mode = rfTune,
                    userValues = list(mtry = mtry, min.node.size = minNodeSize)
                )
            }

            borutaArgs <- list(x = M_df, y = y,
                               maxRuns = borutaMaxRuns,
                               doTrace = borutaDoTrace)

            if(!is.null(rfSet)){
                # --------------------------------------------------------------
                # Boruta 10.0.0 replaced its default importance adapter:
                # getImpRfZ (ranger) became getImpFruZ, backed by the Rust 'fru'
                # package. The two use different parameter vocabularies, and
                # handing ranger's names to fru fails with
                # "unused arguments (num.trees = ..., mtry = ..., ...)".
                #
                #     concept              ranger          fru
                #     number of trees      num.trees       trees
                #     features per split   mtry            tries
                #     minimum leaf size    min.node.size   (not exposed)
                #
                # fru hard-codes the leaf-size threshold at 4 for regression, so
                # min.node.size simply cannot be forwarded. That costs very
                # little: decomposing the tuning gain shows mtry accounts for
                # 76% of it at n=30/p=15, 94% at n=120/p=15 and 99% at
                # n=500/p=40. The larger the design, the more it is mtry alone
                # that matters, so the fru default is kept rather than forcing
                # ranger just to regain min.node.size.
                # --------------------------------------------------------------
                borutaExports <- getNamespaceExports("Boruta")
                bEngine <- if(borutaEngine != "auto"){
                    borutaEngine
                } else if("getImpFruZ" %in% borutaExports &&
                          requireNamespace("fru", quietly = TRUE)){
                    "fru"
                } else {
                    "ranger"
                }

                if(bEngine == "fru" && !("getImpFruZ" %in% borutaExports)){
                    stop("borutaEngine = \"fru\" needs Boruta >= 10.0.0 (which provides getImpFruZ).")
                }
                if(bEngine == "ranger" && !("getImpRfZ" %in% borutaExports)){
                    stop("borutaEngine = \"ranger\" needs a Boruta version providing getImpRfZ.")
                }

                borutaMtry <- max(1L, min(2L * ncol(M_df),
                                          as.integer(round(rfSet$mtry * 2))))

                # --------------------------------------------------------------
                # mtry/tries must be passed through a wrapper rather than as a
                # fixed value, because Boruta's feature space SHRINKS as the
                # run progresses. Its inner loop is
                #
                #     xSha <- x[, decReg != "Rejected", drop = F]
                #     getImp(cbind(x[, decReg != "Rejected"], xSha), y, ...)
                #
                # so once enough parameters are rejected the matrix handed to
                # the importance adapter can have fewer columns than the mtry
                # we chose up front - at which point both fru ("tries ... not
                # larger than the number of columns in x") and ranger error
                # out mid-run. With 40 parameters that happens as soon as more
                # than 20 are rejected, which is the normal outcome of a
                # sensitivity analysis. Clamping per call fixes it.
                # --------------------------------------------------------------
                nTreesB <- rfSet$num.trees
                nNodeB  <- rfSet$min.node.size
                force(borutaMtry); force(nTreesB); force(nNodeB)

                if(bEngine == "fru"){
                    baseImp <- Boruta::getImpFruZ
                    wrappedImp <- function(x, y, ...){
                        baseImp(x, y,
                                trees = nTreesB,
                                tries = min(borutaMtry, ncol(x)),
                                ...)
                    }
                    message(sprintf(
                        "Boruta forest (fru): trees = %d, tries = %d (of %d incl. shadows, clamped as attributes are dropped); min.node.size not supported by fru",
                        nTreesB, borutaMtry, 2 * ncol(M_df)))
                } else {
                    baseImp <- Boruta::getImpRfZ
                    wrappedImp <- function(x, y, ...){
                        baseImp(x, y,
                                num.trees     = nTreesB,
                                mtry          = min(borutaMtry, ncol(x)),
                                min.node.size = nNodeB,
                                ...)
                    }
                    message(sprintf(
                        "Boruta forest (ranger): num.trees = %d, mtry = %d (of %d incl. shadows, clamped as attributes are dropped), min.node.size = %d",
                        nTreesB, borutaMtry, 2 * ncol(M_df), nNodeB))
                }

                # Boruta stores comment(getImp) as the result's impSource
                # field; carry it across so the wrapper stays self-describing.
                comment(wrappedImp) <- comment(baseImp)
                borutaArgs$getImp   <- wrappedImp
            }

            bor <- do.call(Boruta::Boruta, borutaArgs)
            imp <- Boruta::attStats(bor)

            # Align importance table rows with varNames. as.data.frame() may
            # have sanitised the "-epc" suffix back to ".epc", in which case
            # name-based indexing would silently produce a table of NAs, so
            # fall back to positional alignment (attStats rows follow the
            # column order of M_df).
            if(all(varNames %in% rownames(imp))){
                imp <- imp[varNames, , drop = FALSE]
            } else if(nrow(imp) == length(varNames)){
                rownames(imp) <- varNames
            } else {
                stop("Could not align the Boruta importance table with the parameter names.")
            }

            result <- data.frame(
                parameter  = varNames,
                importance = imp$meanImp,
                decision   = imp$decision,
                row.names  = NULL,
                stringsAsFactors = FALSE
            )
            write.csv(file = outputFile, x = result, row.names = FALSE)

            # Normalise importance to [0,1] for the plot
            maxImp <- max(imp$meanImp, na.rm = TRUE)
            plotImp <- if(maxImp > 0) imp$meanImp / maxImp else imp$meanImp

            plotData <- data.frame(
                name       = varNames,
                importance = plotImp,
                decision   = imp$decision,
                stringsAsFactors = FALSE
            )

            sensiPlot <- ggplot(plotData, aes(x = name, y = importance,
                                              fill = decision)) +
                geom_bar(stat = 'identity') +
                scale_fill_manual(
                    values = c("Confirmed" = "steelblue",
                               "Tentative" = "gold",
                               "Rejected"  = "tomato"),
                    name   = "Boruta decision",
                    drop   = FALSE
                ) +
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab(NULL) +
                ylab("Relative importance") +
                ggtitle(plotTitle)
            print(sensiPlot)
            ggsave(plotName, plot = sensiPlot, dpi = dpi)

            if(shap){
                shapRes <- doShap(M_df, y, varNames, rfSet)
                return(invisible(list(boruta = bor,
                                      borutaImportance = result,
                                      shap = shapRes,
                                      rfSettings = rfSet)))
            }

            return(invisible(bor))
        }
    }

    # -------------------------------------------------------------------------
    # Either run musoMonte internally or read an existing result file.
    #
    # When musoMonte is run internally the full parameter x output matrix is
    # saved to <outLoc>/monte_matrix.csv so it can be reused for subsequent
    # SA runs (different varIndex, different method) without re-running the
    # model.  Pass monteCarloFile = file.path(outLoc, "monte_matrix.csv") to
    # reload it.
    # -------------------------------------------------------------------------
    if(is.null(monteCarloFile)){
        M <- musoMonte(parameters  = parameters,
                      settings    = settings,
                      sourceFile  = NULL,
                      inputDir    = inputDir,
                      outLoc      = outLoc,
                      iterations  = iterations,
                      preTag      = preTag,
                      outputType  = outputType,
                      outVars     = outVars,
                      fun         = fun,
                      varIndex    = varIndex,
                      skipSpinup  = skipSpinup,
                      skipZero    = skipZero,
                      postProcString = postProcString,
                      constraints = NULL,
                      modifyOut   = modifyOut,
                      parallel    = parallel,
                      nCores      = nCores,
                      sampling    = sampling
                      )
        M <- cbind(seq_along(M[, 1]), M)

        # Save the full matrix (all outputs) so it can be reused later
        matrixPath <- file.path(outLoc, "monte_matrix.csv")
        tryCatch(
            write.csv(M, file = matrixPath, row.names = FALSE),
            error = function(e)
                warning("Could not save monte_matrix.csv: ", conditionMessage(e))
        )
        message(sprintf(
            "Monte Carlo matrix saved to '%s'. Reuse with monteCarloFile = \"%s\".",
            matrixPath, matrixPath
        ))

        yInd <- grep("mod.", colnames(M))[varIndex]
        M    <- M[, c(grep("mod.", colnames(M), invert = TRUE), yInd)]
        return(doSensi(M))

    } else {
        M    <- read.csv(monteCarloFile)
        yInd <- grep("mod.", colnames(M))[varIndex]
        M    <- M[, c(grep("mod.", colnames(M), invert = TRUE), yInd)]
        return(doSensi(M))
    }
}
